name: stealth_tracker
description: A stealth background location tracker with Firebase.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0
  geolocator: ^10.0.0
  background_fetch: ^1.1.0
  device_info_plus: ^9.0.2
  battery_plus: ^4.0.2
  connectivity_plus: ^5.0.2

flutter:
  uses-material-design: true
