name: stealth_tracker
description: A stealth tracking app powered by Firebase
publish_to: "none" # This is a private project

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (required)
  firebase_core: ^2.32.0

  # Firebase Realtime Database
  firebase_database: ^10.5.7

  # Firebase Analytics (optional but useful)
  firebase_analytics: ^10.10.7

  # Add other Firebase packages here if needed
  # firebase_auth: ^4.17.7
  # cloud_firestore: ^5.17.7

  # UI and utility packages (optional)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true